row:
    name: Row
    description: Standard full width row.
    icon: fa fa-facebook
    fields:
        label:
            label: Row
            type: section
            span: full
        csssection:
            comment: CSS
            type: section
            span: full
            sectionid:
        id:
            label: Row ID
            type: text
            span: left
        classes:
            label: Row Classes
            type: text
            span: right
        moduleslabel:
            comment: Modules
            type: section
            span: full
        modules:
            label: 
            type: repeater
            icon: fa fa-info
            prompt: Add a new module.
            groups: "~/themes/theme2-mdb/config/sections-repeater/modules.yaml"

